import Head from "next/head";
import Image from "next/image";
//material UI
import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid2";
import BackgroundImage from "@/assests/auth-bg.png";
//components
import Signup from "@/components/forms/signup";
//styles
import Styles from "@/styles/authForm.module.css";

export default function Main() {
  return (
    <>
      <Head>
        <title>Exclusive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box component="section" className={Styles.signup}>
        <Grid container spacing={2}>
          <Grid size={{xs: 12, sm: 12, md: 6, lg: 6, xl: 6}}>
            <Box>
              <Image
                src={BackgroundImage}
                alt="background-image"
                className={Styles.bgImage}
              />
            </Box>
          </Grid>
          <Grid size={{xs: 12, sm: 12, md: 6, lg: 6, xl: 6}}>
            <Signup />
          </Grid>
        </Grid>
      </Box>
    </>
  );
}
