import Head from "next/head";
import { getSession } from "next-auth/react";
import { GetServerSidePropsContext } from "next";
//Toast
import { ToastContainer } from "react-toastify";
//Components
import Login from "./login";
import "react-toastify/dist/ReactToastify.css";

export default function Main() {
  return (
    <>
      <Head>
        <title>Exclusive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
      <ToastContainer />
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  return {
    redirect: {
      destination: "/home",
      permanent: false,
    },
  };
}
